# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20171112_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_number_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='address',
            name='town',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
