# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
