# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171118_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
